#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# コミット前に自動的にdeno fmtとlintを実行
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.ts$' || true)
if [ -n "$files" ]; then
  echo "Running deno fmt..."
  deno fmt $files
  # ファイルをステージング領域に再度追加
  echo $files | xargs git add
  
  echo "Running deno lint..."
  deno lint $files || {
    echo "Lintエラーが発生しました。修正してください。"
    exit 1
  }
fi